In [4]:
from layers import *
%pylab inline
import tensorflow as tf
x = tf.Variable(tf.random_normal([2, 1, 1, 4], stddev=0.01))
r=2
bsize, a, b, c = x.get_shape().as_list()
X_1 = scala_transfer(x,r)
with tf.Session()as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(x)[0])
    print(sess.run(tf.shape(x)))

    print(sess.run(X_1)[0])
    print(sess.run(tf.shape(X_1)))
    



Populating the interactive namespace from numpy and matplotlib
[[[ 0.00546899  0.01181663  0.0192248   0.00712632]]]
[2 1 1 4]
[[[ 0.00546899]
  [ 0.0192248 ]]

 [[ 0.01181663]
  [ 0.00712632]]]
[2 2 2 1]


/anaconda/lib/python3.6/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['flatten']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"
